#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: sync-git-auth
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: tanzu-sync-secrets
type: Opaque
data:
  username: #@ base64.encode(data.values.secrets.sops.git.https.username)
  password: #@ base64.encode(data.values.secrets.sops.git.https.password)