#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git
  annotations:
    tekton.dev/git-0: #@ data.values.imported.git.host 
type: Opaque
stringData:
  username: #@ data.values.imported.git.username
  password: #@ data.values.imported.git.password
  caFile: #@ data.values.tap_values.shared.ca_cert_data