#@ load("@ytt:data", "data")
#@ load("settings_xml.star", "settings_xml")
---
apiVersion: v1
kind: Secret
metadata:
  name: maven-settings
type: service.binding/maven
stringData:
  type: maven
  provider: sample
  settings.xml: #@ settings_xml(data.values.imported.maven.url, getattr(data.values.imported.maven, "password", None), getattr(data.values.imported.maven, "username", None))
